language: go

sudo: false

go:
  - 1.4.2
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get github.com/WindomZ/cli-mate

install:
  - go install

before_script:
  - cd ./tests

script:
  - go test -v ./...
